#######################################
# Example MultiQC Configuration File
#######################################

# This file can be saved either in the MultiQC installation
# directory, or as ~/.multiqc_config.yaml

# Configuration settings are taken from the following locations, in order:
# - Hardcoded in MultiQC (multiqc/utils/config.py)
# - <installation_dir>/multiqc_config.yaml
# - ~/.multiqc_config.yaml
# - Command line options

---
# Title to use for the report.
title: "S. latissima genome statistics"

# Disable the analysis paths and time in the report header
show_analysis_paths: False
show_analysis_time: False

# Output filenames
output_fn_name: multiqc_report.html
data_dir_name: multiqc_data

# Whether to create the parsed data directory in addition to the report
make_data_dir: True

# Ignore files larger than this when searching for logs (bytes)
log_filesize_limit: 5000000

# MultiQC skips a couple of debug messages when searching files as the
# log can get very verbose otherwise. Re-enable here to help debugging.
report_readerrors: False
report_imgskips: False

# Opt-out of remotely checking that you're running the latest version
no_version_check: True

# How to plot graphs. Different templates can override these settings, but
# the default template can use interactive plots (Javascript using HighCharts)
# or flat plots (images, using MatPlotLib). With interactive plots, the report
# can prevent automatically rendering all graphs if there are lots of samples
# to prevent the browser being locked up when the report opens.
plots_force_flat: False # Try to use only flat image graphs
plots_force_interactive: False # Try to use only interactive javascript graphs
plots_flat_numseries: 100 # If neither of the above, use flat if > this number of datasets
num_datasets_plot_limit: 50 # If interactive, don't plot on load if > this number of datasets
max_table_rows: 500 # Swap tables for a beeswarm plot above this


# Overwrite module filename search patterns. See multiqc/utils/search_patterns.yaml
# for the defaults. Remove a default by setting it to null.
# sp:
#   busco:
#     fn: "aug_busco*/short_summary*"
#   quast:
#     fn: "quast_*/report.tsv"
  

# Change module order
module_order:
  - busco:
      name: "BUSCO (Euk)"
      anchor: "busco_euk"
      info: "eukaryota"
      target: ""
      path_filters:
        - "short_summary.specific.eukaryota_*"
  - busco:
      name: "BUSCO (Stra)"
      anchor: "busco_stra"
      info: "stramenopiles"
      path_filters:
        - "short_summary.specific.stramenopiles_*"
  - quast:
      name: "QUAST"
      anchor: "quast"
      info: "quast"

