os: linux
arch:
 - amd64
 - ppc64le
language: python
python:
  - "2.7"
  - "3.6"

compiler:
  - gcc
  - clang

before_script:
  - pip install networkx==2.2

script: 
  - make; make dependencies
  - python scripts/run-tests.py
